# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(455, 313)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/3_books_64x64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 451, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(128, 128))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/3_books_64x64.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.aboutLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.aboutLabel.setTextFormat(QtCore.Qt.RichText)
        self.aboutLabel.setIndent(-1)
        self.aboutLabel.setObjectName("aboutLabel")
        self.horizontalLayout.addWidget(self.aboutLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.aboutLabel.setText(_translate("Dialog", "About the application..."))
        self.textEdit.setHtml("""<!DOCTYPE html>
<html lang="en">
<head>
    <style type="text/css">
        p { margin: 0.5em; }
        body { background-color: darkgray, color: black;}
    </style>
</head>
<body>
<p>ihe-sync is a simple tool to keep locally all the documents in sync.</p>
<p>Please, visit the <a href="https://www.ihe.net">IHE website</a>.
</p>
<p>It's an open source project, by <a href="https://www.opikanoba.org">Fr&eacute;d&eacute;ric Laurent</a>,
    hosted on <a href="https://github.com/flrt/ihe-tf-sync">Github</a>.</p>
<p>Feel free to contact me, report bug or ask for improvements.</p>
<p>These software is distributed under GPL License.</p>
<p>It uses :</p>
<ul>
    <li>Qt</li>
    <li>pyqt5</li>
    <li>requests</li>
    <li>beautifulsoup4</li>
    <li>html5lib</li>
    <li>cx_Freeze</li>
</ul>

</body>
</html>
        """)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
