DOMAIN_DICT = {
    "CARD": "Cardiology",
    "DENT": "Dental",
    "ENDO": "Endoscopy",
    "EYECARE": "Eye Care",
    "ITI": "IT Infrastructure",
    "LAB": "Laboratory (obsolete see PALM)",
    "PALM": "Pathology and Laboratory Medicine",
    "PAT": "Anatomic Pathology",
    "PCC": "Patient Care Coordination",
    "PCD": "Patient Care Device",
    "PHARMACY": "Pharmacy",
    "PHDSC": "Public Health Data Standards Consortium",
    "QRPH": "Quality, Research and Public Health",
    "QUALITY": "Quality",
    "RAD": "Radiology",
    "RO": "Radiation Oncology",
    "SUPPL": "Supplements",
    "TF": "other",
}